version: "3"

volumes:
  dbdata:

services:
  competition:
    build:
      context: ./competition
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DB_HOST=${HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

  auth:
    build:
      context: ./auth
    restart: always
    ports:
      - "80:8080"
    environment:
      - HOST=${HOST}
      - PORT=8080
      - COMPETITION_PORT=8081

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
