version: "3"
services:
  competition:
    build:
      context: ./competition
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

  auth:
    build:
      context: ./auth
    ports:
      - "8080:8080"
    environment:
      - HOST=host.docker.internal
      - PORT=8080
      - COMPETITION_PORT=8081
